### ISSUE TITLE
cleanup script

### ISSUE THREAD

**Issue by srinandan** [edgemicro-kubernetes/edgemicro-k8#5]
https://github.com/edgemicro-kubernetes/edgemicro-k8/blob/master/docker/edgemicro_proxy_init/prepare_proxy.sh

this script refers to envoy rules that don't apply to us (i think)

**Comment by rajeshm7910** [comment]
Fixed this. It now has EDGEMICRO rules. Although taken from istio, i had to tweek routing rules for edgemicro.
